# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: alexx2000.DoubleCommander
PackageVersion: 1.0.6
MinimumOSVersion: 10.0.0.0
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2022-06-04
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://github.com/doublecmd/doublecmd/releases/download/v1.0.6/doublecmd-1.0.6.i386-win32.exe
  InstallerSha256: 439F7E7994840811496FFA2E39FD01EA2B97388B4BB7DB9212597072E0DE484A
- Architecture: x86
  InstallerType: wix
  InstallerUrl: https://github.com/doublecmd/doublecmd/releases/download/v1.0.6/doublecmd-1.0.6.i386-win32.msi
  InstallerSha256: D057E0937294492048FA9228D7C34B544685181A5040C52E08CA3AF400D827F9
  ProductCode: '{98F98F28-58DD-4E30-A250-72D041BE1CB1}'
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/doublecmd/doublecmd/releases/download/v1.0.6/doublecmd-1.0.6.x86_64-win64.exe
  InstallerSha256: 7D753A5DBD2DBF4DC35752DCE26DB994E2FCD55875CEEAFC065F3B4D64F04793
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/doublecmd/doublecmd/releases/download/v1.0.6/doublecmd-1.0.6.x86_64-win64.msi
  InstallerSha256: 83D28EA57BC6B6316462BE560B32F4F71EB794EEEEC4FDB351EEAB204B7BF980
  ProductCode: '{85CA9A3A-364D-45A6-8A89-397042E238A9}'
ManifestType: installer
ManifestVersion: 1.1.0
